<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Order\AddItem\" />
    <Folder Include="Order\IncreaseItemCount\" />
    <Folder Include="Order\DecreaseItemCount\" />
    <Folder Include="Order\ApplyDiscount\" />
    <Folder Include="Order\RemoveDiscount\" />
    <Folder Include="Order\SetShippingMethod\" />
    <Folder Include="Order\SetAddress\" />
    <Folder Include="Order\RemoveItem\" />
    <Folder Include="Product\AddSpecification\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.Aplication\Common.Aplication.csproj" />
    <ProjectReference Include="..\Common\Common.Domain\Common.Domain.csproj" />
    <ProjectReference Include="..\Shop.Domain\Shop.Domain.csproj" />
  </ItemGroup>

</Project>
