<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>6f35de17-4727-4367-b993-d171ccde8b9b</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
		<PackageReference Include="MediatR" Version="14.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.12" />
		<PackageReference Include="Serilog" Version="4.4.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="Serilog.Sinks.MSSqlServer" Version="10.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.2" />

		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />

		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />

		<PackageReference Include="UAParser" Version="3.1.47" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Common\Common.AspNetCore\Common.AspNetCore.csproj" />
		<ProjectReference Include="..\..\..\Common\Common.Aplication\Common.Aplication.csproj" />
		<ProjectReference Include="..\..\..\Common\Common.Domain\Common.Domain.csproj" />
		<ProjectReference Include="..\..\..\Shop.Application\Shop.Application.csproj" />
		<ProjectReference Include="..\..\..\Shop.Infrastructure\Shop.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\Shop.Presentation.Facade\Shop.Presentation.Facade.csproj" />
		<ProjectReference Include="..\..\Shop.Config\Shop.Config.csproj" />
		<ProjectReference Include="..\..\..\Shop.Query\Shop.Query.csproj" />
	</ItemGroup>

</Project>